# Generated by Django 6.0.2 on 2026-03-31 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('mid_term_marks', models.FloatField(default=0)),
                ('assignment_score', models.FloatField(default=0)),
                ('class_participation', models.FloatField(default=0)),
                ('activity_participation', models.CharField(default='no', max_length=50)),
                ('aggregate_academic_score', models.FloatField(default=0)),
                ('training_attendance', models.CharField(default='no', max_length=50)),
                ('training_score', models.FloatField(default=0)),
                ('feedback_rating', models.FloatField(default=0)),
                ('pre_training_score', models.FloatField(default=0)),
                ('post_training_score', models.FloatField(default=0)),
                ('improvement', models.FloatField(default=0)),
                ('performance_label', models.CharField(default='Average', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
        ),
    ]
